services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: marbl_u
      POSTGRES_PASSWORD: marbl_p
      POSTGRES_DB: b_declarative
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: